-- Add sample destinations
INSERT INTO destinations (name, slug, description, short_description, country, city, popular, status) VALUES
('Dubai, Emirates', 'dubai-emirates', 'Experience the luxury and modern marvels of Dubai with its iconic skyline, world-class shopping, and desert adventures. From the towering Burj Khalifa to the pristine beaches, Dubai offers a perfect blend of tradition and innovation.', 'Luxury destination with modern attractions', 'UAE', 'Dubai', TRUE, 'active'),
('Paris, France', 'paris-france', 'Discover the city of love with its iconic landmarks, charming cafes, and romantic atmosphere. Walk along the Seine River, visit the Eiffel Tower, and explore world-class museums like the Louvre.', 'The city of love and lights', 'France', 'Paris', TRUE, 'active'),
('Bali, Indonesia', 'bali-indonesia', 'Tropical paradise with beautiful beaches, ancient temples, and vibrant culture. Experience traditional Balinese hospitality, stunning rice terraces, and world-class surfing spots.', 'Tropical paradise with rich culture', 'Indonesia', 'Bali', TRUE, 'active'),
('Tokyo, Japan', 'tokyo-japan', 'Modern metropolis where ancient traditions meet cutting-edge technology. Experience authentic sushi, visit historic temples, and enjoy the vibrant nightlife of this incredible city.', 'Where tradition meets innovation', 'Japan', 'Tokyo', TRUE, 'active'),
('Santorini, Greece', 'santorini-greece', 'Breathtaking Greek island famous for its white-washed buildings, blue-domed churches, and spectacular sunsets. Enjoy wine tasting, volcanic beaches, and Mediterranean cuisine.', 'Iconic Greek island paradise', 'Greece', 'Santorini', TRUE, 'active');

-- Add sample tours
INSERT INTO tours (title, slug, destination_id, description, short_description, price, discount_price, duration_days, duration_nights, max_people, featured_image, inclusions, exclusions, itinerary, difficulty_level, tour_type, featured, popular, status, availability_start, availability_end, meta_title, meta_description) VALUES

('Dubai Desert Safari & City Tour', 'dubai-desert-safari-city-tour', 1, 'Experience the best of Dubai with our comprehensive tour package. Start your adventure with a thrilling desert safari including dune bashing, camel riding, and a traditional BBQ dinner under the stars. Explore Dubai''s modern landmarks including Burj Khalifa, Dubai Mall, and the stunning Palm Jumeirah. This tour perfectly combines adventure, culture, and luxury for an unforgettable Dubai experience.', 'Ultimate Dubai adventure with desert safari and city highlights', 899.00, 799.00, 4, 3, 8, 'assets/images/tours/dubai-tour.jpg', '["Hotel pickup and drop-off", "Professional tour guide", "Desert safari with BBQ dinner", "Burj Khalifa tickets", "Dubai Mall visit", "All transportation"]', '["International flights", "Personal expenses", "Optional activities", "Travel insurance"]', '[{"day": 1, "title": "Arrival & Dubai Mall", "description": "Airport pickup, hotel check-in, visit Dubai Mall and Burj Khalifa"}, {"day": 2, "title": "Desert Safari", "description": "Full day desert safari with dune bashing, camel riding, and BBQ dinner"}, {"day": 3, "title": "City Tour", "description": "Visit Palm Jumeirah, Dubai Marina, and traditional souks"}, {"day": 4, "title": "Departure", "description": "Hotel checkout and airport transfer"}]', 'easy', 'city', 1, 1, 'active', '2025-01-01', '2025-12-31', 'Dubai Desert Safari & City Tour - 4 Days', 'Experience Dubai with desert safari, city tour, and luxury attractions'),

('Paris Romantic Getaway', 'paris-romantic-getaway', 2, 'Fall in love with the City of Light on this romantic 5-day Paris adventure. Visit iconic landmarks like the Eiffel Tower, Louvre Museum, and Notre-Dame Cathedral. Enjoy Seine River cruises, charming café visits, and strolls through Montmartre. This tour includes skip-the-line tickets to major attractions and a romantic dinner cruise. Perfect for couples seeking an unforgettable Parisian experience.', 'Romantic 5-day Paris tour with iconic landmarks and Seine cruise', 1299.00, 1199.00, 5, 4, 6, 'assets/images/tours/paris-tour.jpg', '["4-star hotel accommodation", "Daily breakfast", "Skip-the-line museum tickets", "Seine River dinner cruise", "Professional guide", "Airport transfers"]', '["International flights", "Lunch and dinner (except cruise)", "Personal shopping", "Travel insurance"]', '[{"day": 1, "title": "Arrival & Eiffel Tower", "description": "Airport pickup, hotel check-in, evening Eiffel Tower visit"}, {"day": 2, "title": "Louvre & Seine Cruise", "description": "Morning at Louvre Museum, afternoon Seine River cruise"}, {"day": 3, "title": "Montmartre & Sacré-Cœur", "description": "Explore artistic Montmartre district and Sacré-Cœur Basilica"}, {"day": 4, "title": "Versailles Day Trip", "description": "Full day excursion to Palace of Versailles"}, {"day": 5, "title": "Departure", "description": "Last-minute shopping and airport transfer"}]', 'easy', 'cultural', 1, 1, 'active', '2025-01-01', '2025-12-31', 'Paris Romantic Getaway - 5 Days', 'Romantic Paris tour with Eiffel Tower, Louvre, and Seine cruise'),

('Bali Cultural & Beach Experience', 'bali-cultural-beach-experience', 3, 'Discover the magic of Bali with this perfect blend of cultural immersion and beach relaxation. Visit ancient temples like Tanah Lot and Uluwatu, experience traditional Balinese ceremonies, and explore the stunning Tegallalang Rice Terraces. Relax on pristine beaches in Seminyak and Kuta, enjoy world-class spa treatments, and savor authentic Indonesian cuisine. This tour offers the complete Bali experience.', 'Perfect Bali experience combining culture, temples, and beautiful beaches', 799.00, 699.00, 6, 5, 10, 'assets/images/tours/bali-tour.jpg', '["Boutique hotel accommodation", "Daily breakfast", "Temple entrance fees", "Cultural performances", "Spa treatment", "Airport transfers", "Professional guide"]', '["International flights", "Lunch and dinner", "Personal activities", "Travel insurance", "Optional excursions"]', '[{"day": 1, "title": "Arrival & Ubud", "description": "Airport pickup, transfer to Ubud, visit Monkey Forest Sanctuary"}, {"day": 2, "title": "Rice Terraces & Temples", "description": "Visit Tegallalang Rice Terraces and Tirta Empul Temple"}, {"day": 3, "title": "Tanah Lot Sunset", "description": "Explore Tanah Lot Temple and enjoy spectacular sunset"}, {"day": 4, "title": "Beach Day Seminyak", "description": "Transfer to Seminyak, beach relaxation and spa treatment"}, {"day": 5, "title": "Uluwatu & Kecak Dance", "description": "Visit Uluwatu Temple and watch traditional Kecak dance"}, {"day": 6, "title": "Departure", "description": "Last-minute shopping and airport transfer"}]', 'moderate', 'cultural', 1, 1, 'active', '2025-01-01', '2025-12-31', 'Bali Cultural & Beach Experience - 6 Days', 'Bali tour with temples, rice terraces, and beach relaxation'),

('Tokyo Modern & Traditional', 'tokyo-modern-traditional', 4, 'Immerse yourself in the fascinating contrasts of Tokyo, where ultra-modern skyscrapers stand alongside ancient temples. Experience the bustling energy of Shibuya Crossing, the tranquility of Senso-ji Temple, and the culinary delights of Tsukiji Fish Market. This tour includes visits to traditional districts like Asakusa, modern areas like Harajuku, and day trips to nearby Mt. Fuji and Kamakura.', 'Explore Tokyo blend of modern innovation and ancient traditions', 1599.00, 1399.00, 7, 6, 8, 'assets/images/tours/tokyo-tour.jpg', '["4-star hotel accommodation", "Daily breakfast", "JR Pass for transportation", "Mt. Fuji day trip", "Traditional tea ceremony", "Professional English guide"]', '["International flights", "Lunch and dinner", "Personal shopping", "Travel insurance", "Optional activities"]', '[{"day": 1, "title": "Arrival & Asakusa", "description": "Airport pickup, hotel check-in, explore traditional Asakusa district"}, {"day": 2, "title": "Shibuya & Harajuku", "description": "Experience modern Tokyo in Shibuya and trendy Harajuku"}, {"day": 3, "title": "Tsukiji & Imperial Palace", "description": "Early morning fish market visit and Imperial Palace gardens"}, {"day": 4, "title": "Mt. Fuji Day Trip", "description": "Full day excursion to iconic Mt. Fuji and Lake Kawaguchi"}, {"day": 5, "title": "Kamakura Ancient Capital", "description": "Visit historic Kamakura with Great Buddha statue"}, {"day": 6, "title": "Traditional Culture", "description": "Tea ceremony experience and traditional craft workshops"}, {"day": 7, "title": "Departure", "description": "Last-minute shopping in Ginza and airport transfer"}]', 'moderate', 'cultural', 1, 1, 'active', '2025-01-01', '2025-12-31', 'Tokyo Modern & Traditional - 7 Days', 'Tokyo tour with modern attractions and traditional culture'),

('Santorini Sunset Paradise', 'santorini-sunset-paradise', 5, 'Experience the breathtaking beauty of Santorini with this romantic Greek island getaway. Watch world-famous sunsets from Oia, explore the charming villages of Fira and Imerovigli, and relax on unique volcanic beaches. Enjoy wine tasting at local vineyards, take boat trips to volcanic islands, and indulge in delicious Greek cuisine. This tour captures the essence of Greek island paradise.', 'Romantic Santorini tour with stunning sunsets and Greek island charm', 999.00, 899.00, 4, 3, 6, 'assets/images/tours/santorini-tour.jpg', '["Boutique hotel with caldera view", "Daily breakfast", "Wine tasting tour", "Volcano boat trip", "Sunset dinner in Oia", "Airport transfers"]', '["International flights", "Lunch and dinner (except included)", "Personal expenses", "Travel insurance"]', '[{"day": 1, "title": "Arrival & Fira", "description": "Airport pickup, hotel check-in, explore Fira town"}, {"day": 2, "title": "Oia Sunset", "description": "Visit picturesque Oia village for world-famous sunset"}, {"day": 3, "title": "Volcano & Hot Springs", "description": "Boat trip to volcanic islands and natural hot springs"}, {"day": 4, "title": "Wine Tasting & Departure", "description": "Morning wine tasting tour and airport transfer"}]', 'easy', 'beach', 1, 1, 'active', '2025-01-01', '2025-12-31', 'Santorini Sunset Paradise - 4 Days', 'Santorini tour with sunsets, wine tasting, and volcanic islands');

-- Add tour categories
INSERT INTO tour_categories (name, slug, description) VALUES
('Adventure Tours', 'adventure-tours', 'Thrilling adventures and outdoor activities'),
('Cultural Tours', 'cultural-tours', 'Explore local culture and heritage'),
('Beach Tours', 'beach-tours', 'Relaxing beach destinations'),
('City Tours', 'city-tours', 'Urban exploration and city sightseeing'),
('Romantic Tours', 'romantic-tours', 'Perfect getaways for couples'),
('Luxury Tours', 'luxury-tours', 'Premium travel experiences');

-- Link tours to categories
INSERT INTO tour_category_relations (tour_id, category_id) VALUES
(1, 4), (1, 1), -- Dubai: City + Adventure
(2, 5), (2, 3), -- Paris: Romantic + Cultural
(3, 3), (3, 2), -- Bali: Beach + Cultural
(4, 2), (4, 4), -- Tokyo: Cultural + City
(5, 5), (5, 3); -- Santorini: Romantic + Beach
